---
name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build-test-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
          
      # - name: Setup SBT
      #   run: |
      #     echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
      #     echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
      #     curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
      #     sudo apt-get update
      #     sudo apt-get install sbt
          
      - name: Compile
        run: sbt compile
        
      - name: Test
        run: sbt test
        
      - name: Format
        run: sbt scalafmtCheckAll
        continue-on-error: true

      - name: Semantic Release
        id: release
        uses: Byrde/github-reusable-workflows/actions/semantic-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          should-create-release: true

      - name: Setup GitHub Packages credentials
        run: |
          mkdir -p ~/.sbt
          cat > ~/.sbt/.credentials << EOF
          realm=GitHub Package Registry
          host=maven.pkg.github.com
          user=${{ github.actor }}
          password=${{ secrets.GITHUB_TOKEN }}
          EOF

      - name: Publish commons
        run: sbt -Dversion=${{ steps.release.outputs.version }} "commons/publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish logging
        run: sbt -Dversion=${{ steps.release.outputs.version }} "logging/publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish redis-client
        run: sbt -Dversion=${{ steps.release.outputs.version }} "redis-client/publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish pubsub
        run: sbt -Dversion=${{ steps.release.outputs.version }} "pubsub/publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish smtp
        run: sbt -Dversion=${{ steps.release.outputs.version }} "smtp/publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
